---
- hosts: all
  become: true
  tasks:
    - name: Update package lists
      apt: update_cache=yes

    - name: Install PostgreSQL packages
      apt:
        name:
          - postgresql
          - postgresql-contrib
        state: present

    - name: Enable and start PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: yes

